// Icon source: Remix Icon — a hand-crafted open-source icon set with fill/line variants.
// All icons use the Line variant for a clean, consistent stroke style.
// Swappable here in one place.
export {
  RiFireLine as Flame,
  RiTrophyLine as Trophy,
  RiVipCrownLine as Crown,
  RiStarLine as Star,
  RiTimeLine as Clock,
  RiFileCopyLine as Copy,
  RiCheckLine as Check,
  RiCloseLine as X,
  RiSunLine as Sun,
  RiMoonLine as Moon,
  RiGlobeLine as Globe,
  RiMapPinLine as MapPin,
  RiShoppingBagLine as ShoppingBag,
  RiGraduationCapLine as GraduationCap,
  RiArrowRightLine as ArrowRight,
  RiArrowLeftLine as ArrowLeft,
  RiAddLine as Plus,
  RiArrowDownSLine as CaretDown,
  RiArrowRightSLine as CaretRight,
  RiMore2Line as DotsThree,
  RiUserLine as User,
  RiSwordLine as Swords,
  RiTeamLine as Users,
  RiRobotLine as Bot,
  RiSparklingLine as Sparkles,
  RiShareForwardLine as Share2,
  RiMailLine as Mail,
  RiLogoutBoxRLine as LogOut,
  RiRefreshLine as RotateCcw,
  RiArrowGoBackLine as Undo2,
  RiLoader4Line as Loader2,
  RiSpeedUpLine as TrendingUp,
  RiErrorWarningLine as AlertTriangle,
  RiFlashlightLine as Zap,
  RiWifiLine as Wifi,
  RiWifiOffLine as WifiOff,
} from "@remixicon/react";
